name: wiredtogether
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy>=1.26.4
  - gymnasium=0.29.1
  - pettingzoo=1.24.3
  - opencv
  - pytorch
  - tensorboard
  - wandb
  - pip:
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - python-dotenv==1.2.1
      - loguru==0.7.3
      - rich==13.9.4
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - black==23.12.1
      - ruff==0.1.15
      - mypy==1.19.1
      - pre-commit==3.8.0
      - pytest==7.4.4
      - -e ./craftium
